import re
import secrets
import pytest
from cogs.registration import REGISTRATION_COMMAND_REGEX


class TestRegistrationLogic:
    def test_regex_matches_urlsafe_tokens(self):
        """
        The regex must match tokens generated by secrets.token_urlsafe(6).
        These tokens can contain a-z, A-Z, 0-9, _, and -.
        """
        # Test basic alphanumeric
        assert REGISTRATION_COMMAND_REGEX.match("!register abc123XYZ")

        # Test underscore (supported by \w)
        assert REGISTRATION_COMMAND_REGEX.match("!register abc_123")

        # Test hyphen (NOT supported by \w, but required for urlsafe)
        match = REGISTRATION_COMMAND_REGEX.match("!register abc-123")
        assert match, "Regex failed to match token with hyphen"
        assert match.group(1) == "abc-123"

    def test_token_generation_length(self):
        """
        Verify that secrets.token_urlsafe(6) generates exactly 8 characters.
        """
        token = secrets.token_urlsafe(6)
        assert len(token) == 8

    def test_regex_capture_group(self):
        """
        Verify the regex captures the token correctly.
        """
        match = REGISTRATION_COMMAND_REGEX.match("!register MySecretToken")
        assert match
        assert match.group(1) == "MySecretToken"

    def test_regex_with_generated_tokens(self):
        """
        Verify the regex against multiple generated tokens to ensure robustness.
        """
        for _ in range(100):
            token = secrets.token_urlsafe(6)
            match = REGISTRATION_COMMAND_REGEX.match(f"!register {token}")
            assert match, f"Regex failed to match generated token: {token}"
            assert match.group(1) == token
