import re
import secrets
import pytest
from cogs.registration import REGISTRATION_COMMAND_REGEX


class TestRegistrationLogic:
    def test_regex_matches_hex_tokens(self):
        """
        The regex must match tokens generated by secrets.token_hex(6).
        These tokens contain lowercase hex digits (0-9, a-f).
        """
        # Test basic hex
        assert REGISTRATION_COMMAND_REGEX.match("!register a1b2c3d4e5f6")

        # The regex still supports generic characters, test those as well for backward compatibility
        assert REGISTRATION_COMMAND_REGEX.match("!register abc_123")
        assert REGISTRATION_COMMAND_REGEX.match("!register abc-123")

    def test_token_generation_length(self):
        """
        Verify that secrets.token_hex(6) generates exactly 12 characters.
        """
        token = secrets.token_hex(6)
        assert len(token) == 12

    def test_regex_capture_group(self):
        """
        Verify the regex captures the token correctly.
        """
        match = REGISTRATION_COMMAND_REGEX.match("!register a1b2c3d4e5f6")
        assert match
        assert match.group(1) == "a1b2c3d4e5f6"

    def test_regex_with_generated_tokens(self):
        """
        Verify the regex against multiple generated tokens to ensure robustness.
        """
        for _ in range(100):
            token = secrets.token_hex(6)
            match = REGISTRATION_COMMAND_REGEX.match(f"!register {token}")
            assert match, f"Regex failed to match generated token: {token}"
            assert match.group(1) == token
